name: Lint Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'reporting-page/frontend/**'
      - '.github/workflows/frontend-lint.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'reporting-page/frontend/**'
      - '.github/workflows/frontend-lint.yml'

permissions:
  checks: write
  contents: write
  
jobs:
  run-linters:
    name: Lint Frontend
    runs-on: windows-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4

      - run: ls

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'reporting-page/frontend/package-lock.json'
        
      - run: ls
      - run: cd .\reporting-page\
      - run: ls
      - name: Install Node.js dependencies
        run: npm ci
          
      - run: frontend
          
      # ESLint and stylelint configuration in `reporting-page/frontend/package.json`
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_args: "**/*.js"
          stylelint: true
          stylelint_args: "**/*.css"