name: Lint Frontend

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'reporting-page/frontend/**'
      - '.github/workflows/frontend-lint.yml'

permissions:
  contents: write
  checks: write
  
jobs:
  run-linters:
    name: Lint Frontend
    runs-on: windows-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'reporting-page/frontend/package-lock.json'
        
      - name: Install Node.js dependencies
        run: npm ci
        working-directory: reporting-page/frontend

        # ESLint and stylelint configuration in `reporting-page/frontend/package.json`
      - name: Run ESLint
        run: npx eslint **/*.js
        if: always()
        working-directory: reporting-page/frontend
        
      - name: Run Stylelint
        run: npx stylelint **/*.css
        working-directory: reporting-page/frontend
        if: always()