name: Lint Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'reporting-page/frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'reporting-page/frontend/**'
      - '.github/workflows/**'

permissions:
  checks: write
  contents: write
  
jobs:
  run-linters:
    name: Lint Frontend
    runs-on: windows-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        
      - run: cd reporting-page

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
    
      - name: Install Node.js dependencies
        run: npm install; npm ci
          
      - run: frontend
          
      # ESLint and stylelint configuration in `reporting-page/frontend/package.json`
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_args: "**/*.js"
          stylelint: true
          stylelint_args: "**/*.css"