name: Generate Installer
on:
  push:
    tags:
      - 'v*.*.*' # Match version tags

jobs:
  build:
    name: Generate Installer
    runs-on: windows-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        
      - name: Set version variable
        shell: pwsh
        run: |
          $VERSION = (git describe --tags (git rev-list --tags --max-count=1)) -replace "^v", ""
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
      
      - name: Set up Go  
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'reporting-page/frontend/package-lock.json'

      - name: Install wails    
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.8.1

      - name: Setup Go workspace
        run: ./setup_go_work.bat

      - name: Build executables
        run: .\build.bat
        
      - name: Generate installer using Inno Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: generate-installer.iss
          options: /DMyAppVersion=${{ env.VERSION }}
      
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          files: InfoSec-Agent-*-Setup.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true