name: Lint Backend

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**/*.go'
      - '.github/workflows/golangci-lint.yml' 

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    name: Lint Backend
    runs-on: windows-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 1
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

        with:
          go-version: '1.22.0'

      - name: Make lint result directory
        run: mkdir linting

      - name: Make dummy file for reporting-page linting
        run: New-Item -Force reporting-page/frontend/dist/index.html

      - name: Setup Go workspace
        run: ./setup_go_work.bat

      - name: Run linter on InfoSec-Agent backend
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

          args: --out-format=json:linting/lint-report-InfoSec-Agent.json,colored-line-number,github-actions

          only-new-issues: false

          # Optional: if set to true, then all caching functionality will be completely disabled,
          #           takes precedence over all other caching options.
          skip-cache: false

          # Optional: if set to true, then the action won't cache or restore ~/go/pkg.
          skip-pkg-cache: false

          # Optional: if set to true, then the action won't cache or restore ~/.cache/go-build.
          skip-build-cache: false

      - name: Run linter on reporting-page backend
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

          working-directory: reporting-page
          args: --out-format=json:../linting/lint-report-reporting-page.json,colored-line-number,github-actions
          
          only-new-issues: false
          
          skip-cache: false
          skip-pkg-cache: false
          skip-build-cache: false
        if: always()
        
      - name: Upload linter output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: golangci-lint-output
          path: ${{ github.workspace }}/linting
        if: always()