name: Go Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  go-test:
    runs-on: windows-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Run tests
      # skip the integration_testing directory, because these tests are run on VM's with custom configurations
      # skip TestFindEntriesValidInput because it opens the registry, which is different in the GitHub Actions runner
      run: go test -cover $(go list ./... | grep -v /backend/integration_testing)
