name: Go Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '!**/*.go'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '!**/*.go'

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'
    - name: Run tests
      run: go test -cover -skip TestFindEntriesValidInput ./...
